language: node_js
node_js:
  - "stable"
  - "8"
  - "6"
script: make travis-test
matrix:
  fast_finish: true
  include:
    - env: BENCHMARK=true
      script: "node benchmark/benchmark.js --regex '^(?!.*highmem)'"
